### ISSUE TITLE
Numerous Issues

### ISSUE THREAD

**Issue by jwilczek** [brad-richardson/ecobee-csv#1]
I've been reviewing your code and trying to use it for a project. I've noticed several issues/bugs. Are you still using this? If so, I'd like to pass along my findings.

**Comment by brad-richardson** [comment]
I have it running every day although I haven’t developed on it for a while. I would love any feedback or bugs you may have, feel free to file separate issues or comment here or do a pull request, whatever you feel is appropriate.

**Comment by jwilczek** [comment]
It took me a while to get it running and then I realized it was only setup for a single thermostat. Once I saw how easy creating and app and performing auth was, I have since moved on to my own solution.

However, I have some feedback and thoughts from looking at your code that may (or may not) be of interest to you.

1) there is not error checking in config.py. if the config file does not exist the setup errors out. 

2) there are handful of places that could benefit from error checking

3) the biggest issue i noticed  (and this almost had me pulling my hair out) is this line from ecobee-csv.py
`CSV_HEADER_ROW = "Date,Time,ID," + ','.join(list(COLUMNS.values()))`

Specifically, "list(COLUMNS.values())" does not give the same order everytime (at least for me).

This is also an issue later on in __fetch_data()
`columns_csv = ','.join(list(COLUMNS.keys()))`

Since the data is returned in the order requested, the random ordering was causing mismatches between column headers and the data. Did you ever notice similar issues?

Both of these issues can be resolved by adding a call to sorted, i.e., 
`
columns_keys = sorted(list(COLUMNS.keys()))
columns_csv = ','.join(sorted(list(COLUMNS.keys())))
`

**Comment by brad-richardson** [comment]
Sorry it has taken me so long to look at this. I appreciate you taking the time to list these out and debug my code! I now add the config file if it doesn't exist and have a fixed order on the columns (I never had issues but shouldn't have relied on the dictionary key ordering). I definitely could use more error checking throughout but hopefully that fixes most of the biggest pain points. Closing, I'll try to add more error handling in the future
